//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AesDfApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeDBEntities1 : DbContext
    {
        public EmployeeDBEntities1()
            : base("name=EmployeeDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Student_table> Student_table { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    }
}
